/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_thrift_ProcessFunction */

#ifndef _Included_org_apache_thrift_ProcessFunction
#define _Included_org_apache_thrift_ProcessFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_thrift_ProcessFunction
 * Method:    HelloWorld
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_thrift_ProcessFunction_HelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
